# General settings
general:
  - iterations: 30
    name: YAML generator
    input: ./testing/lamp_simple_centos8/
    output: ./testing_output/

# Static values
static:
  - repository: "http://github.com/bennojoy/mywebapp.git"

# Dynamic values
dynamic:
  - network: 192.168.<#>.0/24
    ports: 2042-5142
    password: ./include/passwords.txt