# General settings
general:
  - iterations: 3
    name: YAML generator
    input: ./testing
    output: ./testing_output

# Static values
static:
  - name: "Test"

# Dynamic values
dynamic:
  - network: 192.168.1.0/24
    ports: 2042-5142
    password: ./include/passwords.txt