# General settings
general:
  - iterations: 30
    name: YAML generator
    input: ./app_test/input/lamp_simple_centos8/
    output: ./app_test/output/

# Static values
static:
  - repository: "http://github.com/bennojoy/mywebapp.git"

# Dynamic values
dynamic:
  - ntpserver: 192.168.<#>.0/26
    httpd_port: 2042-5142
    upassword: ./include/test/source/passwords.txt